<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// @codingStandardsIgnoreFile

/** @var \Magento\Sales\Block\Order\History $block */
?>
<?php $productcollection = $block->getProductCollection();

$formatCurrency = $this->helper('Magento\Framework\Pricing\Helper\Data');
foreach ($productcollection as $product) {
    if(isset($product)) {
        $a = $products->getName();
        echo $a;
    }else {
        echo "lỗi";
    }
}
?>
<?= $block->getChildHtml('info') ?>
<?php if ($productcollection && count($productcollection)) : ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?= $block->escapeHtml(__('Product Name #')) ?></th>
                    <th scope="col" class="col date"><?= $block->escapeHtml(__('SKU')) ?></th>
                    <th scope="col" class="col date"><?= $block->escapeHtml(__('Price')) ?></th>
                    <?= $block->getChildHtml('extra.column.header') ?>
                    <th scope="col" class="col total"><?= $block->escapeHtml(__('Commisson Type')) ?></th>
                    <th scope="col" class="col status"><?= $block->escapeHtml(__('Commission Value')) ?></th>
                    <th scope="col" class="col total"><?= $block->escapeHtml(__('Commisson Result')) ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($productcollection as $products) : ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('Product Name #')) ?>" class="col id"><a href="<?= $products->getProductUrl()  ?>"><?= $block->escapeHtml($products->getName()) ?></a></td>
                        <td data-th="<?= $block->escapeHtml(__('SKU')) ?>" class="col date"><?= /* @noEscape */ $block->escapeHtml($products->getSku()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Price')) ?>" class="col date"><?= /* @noEscape */ $formatCurrency->currency($products->getPrice()) ?></td>
                        <?php $extra = $block->getChildBlock('extra.container'); ?>
                        <?php if ($extra) : ?>
                            <?php $extra->setOrder($products); ?>
                            <?= $extra->getChildHtml() ?>
                        <?php endif; ?>
                        <td data-th="<?= $block->escapeHtml(__('Commisson Type')) ?>" class="col total">
                            <?php /* @noEscape */ $typeCommisson = $products->getCommissionType();
                            if ($typeCommisson == 1) {
                                echo 'Fixel';
                            } else {
                                echo 'Percent';
                            }

                            ?></td>
                        <?php /* @noEscape */ $typeCommisson = $products->getCommissionType();
                        if ($typeCommisson == 1) { ?>
                            <td data-th="<?= $block->escapeHtml(__('Commission Value')) ?>" class="col status">$<?= number_format(($products->getCommissionValue()), 2,".",",")  ?></td>
                        <?php } else {    ?>
                            <td data-th="<?= $block->escapeHtml(__('Commission Result')) ?>" class="col status"><?= number_format(($products->getCommissionValue()), 2,".",",")  ?> %</td>
                        <?php     }

                        ?></td>
                        <?php /* @noEscape */ $typeCommisson = $products->getCommissionType();
                        if ($typeCommisson == 1) { ?>
                            <td data-th="<?= $block->escapeHtml(__('Commission Result')) ?>" class="col status"><?= $formatCurrency->currency($products->getCommissionValue(), true, false)  ?></td>
                        <?php } else {    ?>
                            <td data-th="<?= $block->escapeHtml(__('Commission Result')) ?>" class="col status"><?= $formatCurrency->currency( ($products->getCommissionValue() * $products->getPrice()/100 ), true, false)  ?></td>
                        <?php     }

                        ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml($block->getEmptyOrdersMessage()) ?></span></div>
<?php endif ?>
